<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>Grupo Industrial CL</Company>
    <Product>Gastos de viaje</Product>
    <Authors>Grupo Industrial CL</Authors>
    <NeutralLanguage>es-ES</NeutralLanguage>
  </PropertyGroup>
</Project>
