Attribute VB_Name = "Constantes"
Option Explicit

'------------- CONSTANTES ACCESO DATOS -------
Global Const BD_CRISLAY = "crislaym"
Global Const DSN_CRISLAY = "GALILEO"
Global Const DSN_CRISLAY_CERES = "CERES"
Global Const BD_GESCOM = "gescom"
Global Const DSN_GESCOM = "NEWTON"
Global Const BD_CONTABILIDAD = "contabilidad"
Global Const DSN_CONTABILIDAD = "CONTABILIDAD"
Global Const BD_ONDUPACK = "op_ca2000f"
Global Const DSN_ONDUPACK = "op_ca2000f"
Global Const BD_SQL_ONDUPACK = "Ondupack"
Global Const DSN_SQL_ONDUPACK = "SQL_Ondupack"
Global Const BD_SQL_PERSEIDA = "Perseida"
Global Const DSN_SQL_PERSEIDA = "PERSEIDA"
Global Const BD_SQLSERVER = "Gescom"
Global Const DSN_SQLSERVER = "SqlServer"
Global Const DSN_MYSQLTIENDA = "TiendaOnline"
Global Const DSN_MYSQLTIENDAJOYERIA = "tienda joyeria"
Global Const BD_SQL_GASTOS = "Gastos"
Global Const DSN_SQL_GASTOS = "SQLServer_Gastos"

'------------- CONSTANTES PAISES -------------
Global Const giPAIS_ESPAÑA = 34
Global Const giPAIS_ESPAÑA2 = 35
Global Const giPAIS_PORTUGAL = 51
Global Const giPAIS_ITALIA = 39
Global Const giPAIS_BRASIL = 55
Global Const giPAIS_USA = 1
Global Const giPAIS_PRICO = 9
Global Const giPAIS_MEXICO = 52
Global Const giPAIS_CHILE = 56
Global Const giPAIS_POLONIA = 48
Global Const giPAIS_REINOUNIDO = 44
Global Const giPAIS_CROACIA = 85
Global Const giPAIS_AUSTRIA = 43
Global Const giPAIS_ALEMANIA = 49
Global Const giPAIS_PANAMA = 7
Global Const giPAIS_CRICA = 6
Global Const giPAIS_MARRUECOS = 12
Global Const giPAIS_RCHECA = 42
Global Const giPAIS_VENEZUELA = 58
Global Const giPAIS_TUNEZ = 16
Global Const giPAIS_ARGENTINA = 54
Global Const giPAIS_COLOMBIA = 57
Global Const giPAIS_ANGOLA = 24
Global Const giPAIS_ARGELIA = 13
Global Const giPAIS_NIGERIA = 23
Global Const giPAIS_HONGKONG = 80
Global Const giPAIS_RUMANIA = 40
Global Const giPAIS_TURQUIA = 90
Global Const giPAIS_REPDOM = 8
Global Const giPAIS_ECUADOR = 59
Global Const giPAIS_LIBIA = 18
Global Const giPAIS_PERU = 50
Global Const giPAIS_GUATEMALA = 2
Global Const giPAIS_COSTAMARFIL = 25
Global Const giPAIS_PERSEIDA = 10
Global Const giPAIS_GASEXTREMADURA = 86
Global Const giPAIS_ONDUPACK = 87
Global Const giPAIS_ALTERENERSUN = 88
Global Const giPAIS_PLASTIVERD = 89
Global Const giPAIS_IQOXE = 91
Global Const giPAIS_GES = 92
Global Const giPAIS_LILOTECHNOLOGY = 93
Global Const giPAIS_ONDUPET = 83
Global Const giPAIS_MURCIACARTON = 81
Global Const giPAIS_MATIASGOMA = 82
Global Const giPAIS_AGSIDERURGICABALBOA = 78
Global Const giPAIS_GRUPOGALLARDOBALBOA = 77
Global Const giPAIS_ALFONSOGALLARDO = 76
Global Const giPAIS_CORRUGADOSLASAO = 75
Global Const giPAIS_MARCELIANOMARTIN = 74
Global Const giPAIS_FERROMALLAS = 73
Global Const giPAIS_CORRUGADOSGETAFE = 72
Global Const giPAIS_IQLIT = 71
Global Const giPAIS_GALVACOLOR = 70
Global Const giPAIS_CAMALECOSYSTEMS = 69
Global Const giPAIS_PAPELERASARLANZON = 68
Global Const giPAIS_FUNDACIONRL = 67
Global Const giPAIS_GASILUZ = 66
Global Const giPAIS_CRISTIANLAYDSS = 65
Global Const giPAIS_INDUSTRIASCL = 64
Global Const giPAIS_SOLARSTEEL = 63
Global Const giPAIS_CARTONAJESEXTREMADURA = 62
'NuevoPaisContable

Global Const gsPAIS_ESPAÑA = "España"
Global Const gsPAIS_ESPAÑA2 = "España2"
Global Const gsPAIS_PORTUGAL = "Portugal"
Global Const gsPAIS_ITALIA = "Italia"
Global Const gsPAIS_BRASIL = "Brasil"
Global Const gsPAIS_USA = "U.S.A."
Global Const gsPAIS_PRICO = "P.Rico"
Global Const gsPAIS_MEXICO = "Mexico"
Global Const gsPAIS_CHILE = "Chile"
Global Const gsPAIS_POLONIA = "Polonia"
Global Const gsPAIS_REINOUNIDO = "Reino Unido"
Global Const gsPAIS_CROACIA = "Croacia"
Global Const gsPAIS_AUSTRIA = "Austria"
Global Const gsPAIS_ALEMANIA = "Alemania"
Global Const gsPAIS_PANAMA = "Panama"
Global Const gsPAIS_CRICA = "Costa Rica"
Global Const gsPAIS_MARRUECOS = "Marruecos"
Global Const gsPAIS_RCHECA = "Republica Checa"
Global Const gsPAIS_VENEZUELA = "Venezuela"
Global Const gsPAIS_TUNEZ = "Tunez"
Global Const gsPAIS_ARGENTINA = "Argentina"
Global Const gsPAIS_COLOMBIA = "Colombia"
Global Const gsPAIS_ANGOLA = "Angola"
Global Const gsPAIS_ARGELIA = "Argelia"
Global Const gsPAIS_NIGERIA = "Nigeria"
Global Const gsPAIS_HONGKONG = "Hong Kong"
Global Const gsPAIS_RUMANIA = "Rumania"
Global Const gsPAIS_TURQUIA = "Turquia"
Global Const gsPAIS_REPDOM = "Republica Dominicana"
Global Const gsPAIS_ECUADOR = "Ecuador"
Global Const gsPAIS_LIBIA = "Libia"
Global Const gsPAIS_PERU = "Peru"
Global Const gsPAIS_GUATEMALA = "Guatemala"
Global Const gsPAIS_COSTAMARFIL = "Costa de Marfil"
Global Const gsPAIS_PERSEIDA = "Perseida"
Global Const gsPAIS_GASEXTREMADURA = "Gas Extremadura"
Global Const gsPAIS_ONDUPACK = "Ondupack"
Global Const gsPAIS_ALTERENERSUN = "Alter Enersun"
Global Const gsPAIS_PLASTIVERD = "Plastiverd"
Global Const gsPAIS_IQOXE = "Iqoxe"
Global Const gsPAIS_GES = "GES"
Global Const gsPAIS_LILOTECHNOLOGY = "Lilo Technology"
Global Const gsPAIS_ONDUPET = "Ondupet"
Global Const gsPAIS_MURCIACARTON = "Murcia Cartón"
Global Const gsPAIS_MATIASGOMA = "Matías Gomá"
Global Const gsPAIS_AGSIDERURGICABALBOA = "AG Siderúrgica Balboa"
Global Const gsPAIS_GRUPOGALLARDOBALBOA = "Grupo Gallardo Balboa"
Global Const gsPAIS_ALFONSOGALLARDO = "Alfonso Gallardo"
Global Const gsPAIS_CORRUGADOSLASAO = "Corrugados Lasao"
Global Const gsPAIS_MARCELIANOMARTIN = "Marceliano Martín"
Global Const gsPAIS_FERROMALLAS = "Ferromallas"
Global Const gsPAIS_CORRUGADOSGETAFE = "Corrugados Getafe"
Global Const gsPAIS_IQLIT = "Iqlit"
Global Const gsPAIS_GALVACOLOR = "Galvacolor"
Global Const gsPAIS_CAMALECOSYSTEMS = "Camal Ecosystems"
Global Const gsPAIS_PAPELERASARLANZON = "Papeleras Arlanzón"
Global Const gsPAIS_FUNDACIONRL = "Fundación RL"
Global Const gsPAIS_GASILUZ = "Gasiluz"
Global Const gsPAIS_CRISTIANLAYDSS = "Cristian LAY DSS"
Global Const gsPAIS_INDUSTRIASCL = "Industrias CL"
Global Const gsPAIS_SOLARSTEEL = "Solar Steel"
Global Const gsPAIS_CARTONAJESEXTREMADURA = "Cartonajes Extremadura"

'NuevoPaisContable

Global Const gsPAIS_ESPAÑA_Ingles = "Spain"
Global Const gsPAIS_ESPAÑA2_Ingles = "Spain2"
Global Const gsPAIS_PORTUGAL_Ingles = "Portugal"
Global Const gsPAIS_ITALIA_Ingles = "Italy"
Global Const gsPAIS_BRASIL_Ingles = "Brazil"
Global Const gsPAIS_USA_Ingles = "U.S.A."
Global Const gsPAIS_PRICO_Ingles = "P.Rico"
Global Const gsPAIS_MEXICO_Ingles = "Mexico"
Global Const gsPAIS_CHILE_Ingles = "Chile"
Global Const gsPAIS_POLONIA_Ingles = "Poland"
Global Const gsPAIS_REINOUNIDO_Ingles = "United Kingdom"
Global Const gsPAIS_CROACIA_Ingles = "Croatia"
Global Const gsPAIS_AUSTRIA_Ingles = "Austria"
Global Const gsPAIS_ALEMANIA_Ingles = "Germany"
Global Const gsPAIS_PANAMA_Ingles = "Panama"
Global Const gsPAIS_CRICA_Ingles = "Costa Rica"
Global Const gsPAIS_MARRUECOS_Ingles = "Marruecos"
Global Const gsPAIS_RCHECA_Ingles = "Republica Checa"
Global Const gsPAIS_VENEZUELA_Ingles = "Venezuela"
Global Const gsPAIS_TUNEZ_Ingles = "Tunez"
Global Const gsPAIS_ARGENTINA_Ingles = "Argentina"
Global Const gsPAIS_COLOMBIA_Ingles = "Colombia"
Global Const gsPAIS_ANGOLA_Ingles = "Angola"
Global Const gsPAIS_ARGELIA_Ingles = "Argelia"
Global Const gsPAIS_NIGERIA_Ingles = "Nigeria"
Global Const gsPAIS_HONGKONG_Ingles = "Hong Kong"
Global Const gsPAIS_RUMANIA_Ingles = "Rumania"
Global Const gsPAIS_TURQUIA_Ingles = "Turkey"
Global Const gsPAIS_REPDOM_Ingles = "Republica Dominicana"
Global Const gsPAIS_ECUADOR_Ingles = "Ecuador"
Global Const gsPAIS_LIBIA_Ingles = "Libia"
Global Const gsPAIS_PERU_Ingles = "Peru"
Global Const gsPAIS_GUATEMALA_Ingles = "Guatemala"
Global Const gsPAIS_COSTAMARFIL_Ingles = "Costa de Marfil"
Global Const gsPAIS_PERSEIDA_Ingles = "Perseida"
Global Const gsPAIS_GASEXTREMADURA_Ingles = "Gas Extremadura"
Global Const gsPAIS_ONDUPACK_Ingles = "Ondupack"
Global Const gsPAIS_ALTERENERSUN_Ingles = "Alter Enersun"
Global Const gsPAIS_PLASTIVERD_Ingles = "Plastiverd"
Global Const gsPAIS_IQOXE_Ingles = "Iqoxe"
Global Const gsPAIS_GES_Ingles = "GES"
Global Const gsPAIS_LILOTECHNOLOGY_Ingles = "Lilo Technology"
Global Const gsPAIS_ONDUPET_Ingles = "Ondupet"
Global Const gsPAIS_MURCIACARTON_Ingles = "Murcia Cartón"
Global Const gsPAIS_MATIASGOMA_Ingles = "Matías Gomá"
Global Const gsPAIS_AGSIDERURGICABALBOA_Ingles = "AG Siderúrgica Balboa"
Global Const gsPAIS_GRUPOGALLARDOBALBOA_Ingles = "Grupo Gallardo Balboa"
Global Const gsPAIS_ALFONSOGALLARDO_Ingles = "Alfonso Gallardo"
Global Const gsPAIS_CORRUGADOSLASAO_Ingles = "Corrugados Lasao"
Global Const gsPAIS_MARCELIANOMARTIN_Ingles = "Marceliano Martín"
Global Const gsPAIS_FERROMALLAS_Ingles = "Ferromallas"
Global Const gsPAIS_CORRUGADOSGETAFE_Ingles = "Corrugados Getafe"
Global Const gsPAIS_IQLIT_Ingles = "Iqlit"
Global Const gsPAIS_GALVACOLOR_Ingles = "Galvacolor"
Global Const gsPAIS_CAMALECOSYSTEMS_Ingles = "Camal Ecosystems"
Global Const gsPAIS_PAPELERASARLANZON_Ingles = "Papeleras Arlanzón"
Global Const gsPAIS_FUNDACIONRL_Ingles = "Fundación RL"
Global Const gsPAIS_GASILUZ_Ingles = "Gasiluz"
Global Const gsPAIS_CRISTIANLAYDSS_Ingles = "Cristian LAY DSS"
Global Const gsPAIS_INDUSTRIASCL_Ingles = "Industrias CL"
Global Const gsPAIS_SOLARSTEEL_Ingles = "Solar Steel"
Global Const gsPAIS_CARTONAJESEXTREMADURA_Ingles = "Cartonajes Extremadura"

'NuevoPaisContable

'CONSTANTES ONDUPACK
Global Const giCODJEFEZONA = 1
Global Const giCODJEFEQUIP = 2
Global Const giCODCOMERCIAL = 3
Global Const giCODGERENTE = 4
Global Const giCODCLIENTE = 5
Global Const gi_CteEuros = 166.386

'CONSTANTES TIPOS DISTRIBUIDORAS B
Global Const c_LimiteInferiorDistrib_B_USA = 80
Global Const c_LimiteSuperiorDistrib_B_USA = 160
Global Const c_LimiteInferiorDistrib_B_CRica = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_CRica = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Panama = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Panama = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_RepDominicana = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_RepDominicana = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_PRico = 80
Global Const c_LimiteSuperiorDistrib_B_PRico = 160
Global Const c_LimiteInferiorDistrib_B_Marruecos = 2000
Global Const c_LimiteSuperiorDistrib_B_Marruecos = 1000
Global Const c_LimiteInferiorDistrib_B_Tunez = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Tunez = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Espanya = 15000
Global Const c_LimiteSuperiorDistrib_B_Espanya = 30000
Global Const c_LimiteInferiorDistrib_B_Italia = 180000
Global Const c_LimiteSuperiorDistrib_B_Italia = 350000
Global Const c_LimiteInferiorDistrib_B_Austria = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Austria = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_ReinoUnido = 125 'No especificado
Global Const c_LimiteSuperiorDistrib_B_ReinoUnido = 55 'No especificado
Global Const c_LimiteInferiorDistrib_B_Polonia = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Polonia = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Alemania = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Alemania = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Portugal = 18000
Global Const c_LimiteSuperiorDistrib_B_Portugal = 36000
Global Const c_LimiteInferiorDistrib_B_Mexico = 1000
Global Const c_LimiteSuperiorDistrib_B_Mexico = 1900
Global Const c_LimiteInferiorDistrib_B_Brasil = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Brasil = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Chile = 50000
Global Const c_LimiteSuperiorDistrib_B_Chile = 100000
Global Const c_LimiteInferiorDistrib_B_Croacia = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Croacia = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Rumania = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Rumania = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Venezuela = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Venezuela = 10000000 'No especificado
Global Const c_LimiteInferiorDistrib_B_Colombia = 10000000 'No especificado
Global Const c_LimiteSuperiorDistrib_B_Colombia = 10000000 'No especificado
Global Const RutaIbmserver = "\\clfsv002v\"
